---
title: "Turkey Macroeconomic Dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      bootswatch: flatly
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
#library(flexdashboard)
library(tidyverse)
library(ggplot2)
library(plotly)
library(ggthemes)
library(RColorBrewer)
```


```{r}
### Load Data
load("./analysis/ml_data.Rdata")
load("./df.Rda")
```

Row 
-----------------------------------------------------------------------
### One-month ahead inflation forecast

```{r}
inf_plot <-lasso_preds %>% 
  rename(Actual = CPI,
         Forecasted = pred) %>% 
  gather(key = "Variable", value = "Value", Actual:Forecasted) %>% 
  ggplot(aes(x = Date, y = Value, color = Variable))+
  geom_line(size = 0.5, alpha = 0.75, show.legend = FALSE)+
  scale_color_tableau()+
  theme_clean()+
  scale_y_continuous(labels = scales::percent)+
  scale_x_date(date_breaks = "3 month", date_labels =  "%m %Y")+
  labs(x = "Date",
       y = "",
       title = "",
       caption = "Source: TCMB")+
  theme(plot.title = element_text(face = "italic"))
ggplotly(inf_plot)
```

Row 
-----------------------------------------------------------------------

### Scatter Plot - True Value & Prediction

```{r}
scatter <- lasso_preds %>% 
  ggplot(aes(x = pred, y = CPI))+
  geom_point(size = 2, alpha = 0.8, color = "darkred")+
  geom_abline(intercept = 0, 
              slope = 1, 
              size = 0.3, 
              linetype = 3, 
              alpha = 0.8, 
              color = "midnightblue")+
  theme_clean()+
  scale_y_continuous(labels = scales::percent)+
  scale_x_continuous(labels = scales::percent)+
  labs(x = "Model Prediction",
       y = "True Value",
       caption = "Source: TCMB")
ggplotly(scatter)
  
```

### Residual Analysis

```{r}
residuals <- lasso_preds %>% 
  mutate(Residual = CPI - pred) %>% 
  ggplot(aes(x = Date, y = Residual))+
  geom_point(size = 2, alpha = 0.8, color = "steelblue")+
  geom_ribbon(stat='smooth', se=TRUE, alpha=0.05) +
  geom_line(stat='smooth', alpha=1, color = "darkred")+
  theme_classic() +
  labs(y = "Residual",
       x = "Date",
       title = "")+
  scale_y_continuous(labels = scales::percent)
ggplotly(residuals)


```




```{r}
#df %>%
  #plot_time_series(
    #.date_var = Date,
    #.value = Average_Import_Price*Usd_Try, 
    #.smooth = T, 
    #.smooth_alpha = 0.5, 
    #.smooth_size = 0.7, 
    #.smooth_color = "darkred", 
    #.legend_show = TRUE, 
    #.title = "Average"
  #)


```



```{r}
#df %>%
  #plot_seasonal_diagnostics(.date_var = Date, 
                            #.value = BoP, 
                            #.geom_outlier_color = "darkred", 
                            #.feature_set = "month.lbl")
```






