on:
  schedule:
    - cron: "0 * * * *"
    
jobs:
  build:
    name: refresh the dashboard
    runs-on: ubuntu-18.04 
    container: 
          image: rocker/tidyverse
    steps:
      - name: Query dependencies
        run: |
          install.packages('remotes')
          install.packages('sessioninfo')
          install.packages('XML')
          install.packages('methods')
          install.packages('httr')
          install.packages('xts')
          install.packages('tidyverse')
          install.packages('lubridate')
          install.packages('tidymodels')
          install.packages('ggthemes')
          install.packages('zoo')
          install.packages('PerformanceAnalytics')
          install.packages('forecast')
          install.packages('modeltime')
          install.packages('timetk')
          install.packages('skimr')
          install.packages('quantmod')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Generate raw data
        run: |
          source("raw_data/raw_data.R")
        shell: Rscript {0} 
        
      - name: Generate processed data
        run: |
          source("processed_data/data_processing.R")
        shell: Rscript {0} 
        
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 
