on:
  schedule:
    - cron: "30 10 * * *"
    
jobs:
  build:
    name: refresh the dashboard
    runs-on: ubuntu-22.04 
    container: 
          image: enesgencer18/turkey-macro-dashboard:latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
        with: 
          ref: 'master'        
      - name: Data refresh
        run: |
            bash ./data-refresh/data_refresh.sh "master" 
